<?php
/**
 * AriesPHP languages file example.
 */

$lang['lang_success_1'] = 'You\'ve successfully installed AriesPHP';
$lang['lang_success_2'] = 'Welcome to the MVC world minus the PAIN';
$lang['lang_where_to_start'] = 'Where to Start';
$lang['lang_generated_by'] = 'This page is generated by this code';
$lang['lang_where_to_look'] = 'Where to Look';
$lang['lang_contribute'] = 'Contribute';
$lang['lang_fork_github'] = 'Fork my Github';
$lang['lang_framework_included'] = 'Framework included in AriesPHP';
$lang['lang_licensed'] = 'AriesPHP is released under MIT License';
?>