<div class="container_12">
    <div class="grid_12" id="header">
        <h3>Aries Framework</h3>
    </div>
    <div class="grid_12" id="content">
        <h5>Welcome to Aries Framework for PHP. <?= $hello; ?>.</h5>
        <b>Aries is:</b><br />
        <?php
        echo '<ul>';
        foreach ($features as $feature) {
            echo '<li>'.$feature.'</li>';
        }
        echo '</ul>';
        ?>
        This page is generated by this code:<br />
		<div class="code">
			<b>Controllers</b>: <code>controllers/c_home.php</code><br />
			<b>Views</b>: <code>views/home/v_index.php</code>
		</div>
    </div>
    <div class="grid_12" id="footer">
        Copyright &copy; 2012 Harditya Rahmat Ramadhan
    </div>
</div>