<div class="container_12">
    <div class="grid_12" id="header">
        <h3>Aries Framework</h3>
    </div>
    <div class="grid_12" id="content">
        <h5>Welcome to Aries Framework for PHP. {{hello}}.</h5>
        This page is generated by this code:<br />
        <b>Controllers</b>: <code>controllers/c_home.php</code><br />
        <b>Views</b>: <code>views/home/v_index.php</code>
    </div>
    <div class="grid_12" id="footer">
        Copyright &copy; 2012 Harditya Rahmat Ramadhan
    </div>
</div>