<div class="container gradient_black" style="width:100%;">
    <div class="container">
        <div class="minibox_12" id="header">
            <h3>
                <img src="<?= IMG_DIR ?>logo-aries.png" alt="Logo"/>
            </h3>
        </div>
    </div>
</div>
<div class="container gradient_orange" style="width:100%;">
    <div class="container">
        <div class="minibox_12">
            <br />
        </div>
    </div>
</div>
<div class="container">
    <div class="minibox_12" id="content">
        <h3 id="horay">
            <span class="hello"><?= $horay; ?>.</span><br />
            You've successfully installed AriesPHP.<br />
            Welcome to the MVC world minus the PAIN.
        </h3>
    </div>
    <div class="minibox_6">
        <h3 class="title">Where to Start</h3><br />
        This page is generated by this code:<br />
        <div class="code">
            <b>Controllers</b>: controllers/c_home.php<br />
            <b>Views</b>: views/home/v_index.php
        </div>
    </div>
    <div class="minibox_6">
        <h3 class="title">Where to Look</h3><br />
        <a href="#">MVC Basic.</a><br />
        <a href="#">Insert Javascript, CSS, and Image.</a>
    </div>
</div>
<br />
<div class="container" id="footerContainer">
    <div class="container footer">
        <div class="minibox_4 footer_item">
            <h3>Contribute</h3>
            <a href="https://github.com/freeskys/aries-php" target="_blank">Fork my Github</a>
        </div>
        <div class="minibox_4 footer_item">
            <h3>Developer</h3>
            <a href="https://twitter.com/freeskys">@freeskys</a> - Project Manager and Lead Developer
            <a href="https://twitter.com/androvnugros">@androvnugros</a> - Graphic Designer
        </div>
        <div class="minibox_4 footer_item">
            <h3>Framework included in Aries</h3>
            <a href="https://github.com/uudshan/gemini-css" target="_blank">Minibox System</a> by Moh. Nuruddin Ef.<br />
            <a href="http://jquery.com/" target="_blank">jQuery</a> by The jQuery Foundation<br />
        </div>
    </div>
</div>
<div class="container gradient_orange" id="footerContainer2">
    <div class="container">
        <div class="minibox_12 copyright">
            <br />
            Copyright &copy; 2012 Harditya Rahmat Ramadhan | Aries Micro Framework is released under MIT License.
        </div>
    </div>
</div>